### ISSUE TITLE
encodeMultiSend possibly returning wrong values

### ISSUE THREAD

**Issue by highskore** [gnosis/safe-tasks#7]
## Description

All MultiSend transactions will fail when using the buildMutiSendSafeTx transaction, returning a GS026 error (but the right owner's have signed)

## Environment

- Framework/IDE (e.g. Truffle or Remix): Hardhat
- EVM execution environment / backend / blockchain client: Rinkeby

## Steps to reproduce

Trying to sign any multiSend transactions will end with a GS026 error. Most easily reproducable by cloning this repo and then doing the following commands:

yarn safe create
yarn safe propose-multi <address> tx_input.sample.json
yarn safe sign-proposal <safeTxHash>
yarn safe submit-proposal <safeTxHash>

## Additional context

I'm guessing the encodeMultiSend/encodeMetaTransaction has some errors in it, since it is not covered by tests here.

**Comment by highskore** [comment]
I described the way to reproduce it because the safe-tasks uses the same safe-contracts library for encoding. And's its easier to make a test case that way than me writing a whole source code. But I guess if you prefer, the issue remains for the safe-tasks aswell, althoguh I see  the safe-contract repo as a more imporant one.

Sorry I can't find where the encoding mutlisend was tested. Serching the safe-contract repo only shows me https://github.com/gnosis/safe-contracts/blob/186a21a74b327f17fc41217a927dea7064f74604/test/libraries/MultiSend.spec.ts#L46. 

My env field is filled with my infura infomartion for rinkeby, it works when sending non multisend transactions.

**Comment by highskore** [comment]
.env

```
MNEMONIC=MY_INFURA_PK
INFURA_KEY=MY_INFURA_PROJECT_ID
NODE_URL=INFURA_NODE_URL
NETWORK=rinkeby
```

**Comment by rmeissner** [comment]
All tests related to multisend use `encodeMultiSend` under the hood. Most of the time this is done via `buildMultiSendSafeTx`. 

`GS026` Indicates that during the signing process an invalid signature was produced. Therefore to properly debug this we would have to know the address of the Safe involved and if possible logs.

We regularly use the `safe-tasks` to perform multisend transactions (on different networks). When I tried it right now I get the following output: 
![image](https://user-images.githubusercontent.com/2896048/144714497-5862ec1b-c10a-44b9-a888-8a5ed6ba1b2d.png)

and on Etherscan you can also see that both transactions have been executed via multisend: https://rinkeby.etherscan.io/tx/0xd9bd111526cb3e852e87b166bf1c333da574821edf0d71d280fbd5b84812b7b5#internal

**Comment by highskore** [comment]
Hmm that's pretty weird, are you using the latest version from the master? Just trying to exectue yarn safe submit-proposal without setting --gas-price & --gas-limit returns a transaction witha GS013 error.

https://rinkeby.etherscan.io/tx/0xf1d6b6a7b083c77d212e5f03755f57f8b850eaf92c768150930c8fb997ded858

**Comment by highskore** [comment]
![image](https://user-images.githubusercontent.com/80688826/144715740-11c5fe23-d439-4e9d-a2fd-93ea86ffda2e.png)

**Comment by rmeissner** [comment]
Sorry I should have mentioned, that  I funded the new Safe with 0.1 ETH to avoid GS013

**Comment by lukaracki** [comment]
Here's a transaction that reported a GS026 error. 
https://rinkeby.etherscan.io/tx/0xbe58f3240cc632eb82a638af959734c19fe9f3c6991080764d53b54970a52679

**Comment by rmeissner** [comment]
Thanks, that helps me, I will look into it

**Comment by highskore** [comment]
https://rinkeby.etherscan.io/tx/0x2bfae98c2c13d30e0823fd6f75e4198bda0d792a3159ba4fe570a09e97364c42

Hey I just managed to execute it after funding it. Maybe I was setting that gasLimit wrong. Another thing I was doing is signing it with 2 owners, so that could be a factor. I'll do further testing and let you know.

I tried doing it with two owners now (without setting gasLimit & gasPrice) and it gives me GS013(after funding):

```yarn safe propose-multi 0xe81Cf0e02C7B1DF3413d1f631d3cA07DF8C1a252 tx_input.sample.json
yarn safe sign-proposal 0x01731547b4dbbcb1d87f000ca9c60bc32ab9c9951f225d1fbce7aa083eadba1f --signer-index 1
yarn safe sign-proposal 0x01731547b4dbbcb1d87f000ca9c60bc32ab9c9951f225d1fbce7aa083eadba1f --signer-index 2
yarn safe submit-proposal 0x01731547b4dbbcb1d87f000ca9c60bc32ab9c9951f225d1fbce7aa083eadba1f

An unexpected error occurred:

Error: transaction failed (transactionHash="0xc598c867a99955109e6439a6239a735bfe99e0f03e4f05b6e05aad0829d41085", transaction={"hash":"0xc598c867a99955109e6439a6239a735bfe99e0f03e4f05b6e05aad0829d410...
```

This is the transaction on etherscan: https://rinkeby.etherscan.io/tx/0xc598c867a99955109e6439a6239a735bfe99e0f03e4f05b6e05aad0829d41085.

The transaction input I'm trying to send is:
```
[
  {
    "data": "0x095ea7b3000000000000000000000000c1f3af5dc05b0c51955804b2afc80ef8feed67b9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "to": "0x5eD8BD53B0c3fa3dEaBd345430B1A3a6A4e8BD7C",
    "value": "0",
    "operation": 1
  },
  {
    "data": "0xcc1b4bf600000000000000000000000011b0fd6914efa365ee77c5979dac068fef21db8f00000000000000000000000000000000000000000000000000000000000000640000000000000000000000005ed8bd53b0c3fa3deabd345430b1a3a6a4e8bd7c0000000000000000000000000000000000000000000000000000000061ab95320000000000000000000000000000000000000000000000000000000061abaefa",
    "to": "0xC1f3af5DC05b0C51955804b2afc80eF8FeED67b9",
    "value": "0",
    "operation": 1
  }
]

**Comment by rmeissner** [comment]
I am assuming that the signature sorting is faulty (e.g. influenced by the checksum). I don't have time to debug this today, but latest on monday I will take a look

**Comment by highskore** [comment]
Is it possible that there's something wrong with the transaction data that i'm submitting and that causes GS026?

**Comment by rmeissner** [comment]
Edit: This is for the `GS013`

For your transactions operation should be `0`. Operation `1` will trigger a delegatecall which is not what you want in this case.

I also fail to reproduce your input data. 

I change the content of `tx_input.sample.json` to
```json
[
  {
    "data": "0x095ea7b3000000000000000000000000c1f3af5dc05b0c51955804b2afc80ef8feed67b9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "to": "0x5eD8BD53B0c3fa3dEaBd345430B1A3a6A4e8BD7C",
    "value": "0",
    "operation": 1
  },
  {
    "data": "0xcc1b4bf600000000000000000000000011b0fd6914efa365ee77c5979dac068fef21db8f00000000000000000000000000000000000000000000000000000000000000640000000000000000000000005ed8bd53b0c3fa3deabd345430b1a3a6a4e8bd7c0000000000000000000000000000000000000000000000000000000061ab95320000000000000000000000000000000000000000000000000000000061abaefa",
    "to": "0xC1f3af5DC05b0C51955804b2afc80eF8FeED67b9",
    "value": "0",
    "operation": 1
  }
]
``` 

and run `yarn safe propose-multi 0xe81Cf0e02C7B1DF3413d1f631d3cA07DF8C1a252 tx_input.sample.json` This uses the same Safe you use and therefore should generate the same Safe transaction hash. I get the following:

```
Running on rinkeby
Using Safe at 0xe81Cf0e02C7B1DF3413d1f631d3cA07DF8C1a252
Safe transaction {
  to: '0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761',
  value: 0,
  data: '0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000192015ed8bd53b0c3fa3deabd345430b1a3a6a4e8bd7c00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044095ea7b3000000000000000000000000c1f3af5dc05b0c51955804b2afc80ef8feed67b9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff01c1f3af5dc05b0c51955804b2afc80ef8feed67b9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a4cc1b4bf600000000000000000000000011b0fd6914efa365ee77c5979dac068fef21db8f00000000000000000000000000000000000000000000000000000000000000640000000000000000000000005ed8bd53b0c3fa3deabd345430b1a3a6a4e8bd7c0000000000000000000000000000000000000000000000000000000061ab95320000000000000000000000000000000000000000000000000000000061abaefa0000000000000000000000000000',
  operation: 1,
  safeTxGas: 0,
  baseGas: 0,
  gasPrice: 0,
  gasToken: '0x0000000000000000000000000000000000000000',
  refundReceiver: '0x0000000000000000000000000000000000000000',
  nonce: 0
}
Safe transaction hash: 0xfe54eda4e4ea33c97273803953af2ce2f40a454055455f99ded53b4c59e6cc3e
```

As you can see I get a different Safe transaction hash: `0xfe54eda4e4ea33c97273803953af2ce2f40a454055455f99ded53b4c59e6cc3e` from me and `0x01731547b4dbbcb1d87f000ca9c60bc32ab9c9951f225d1fbce7aa083eadba1f` from you. This indicates that your Safe transaction data is different. If I look at the Ethereum tx you shared I also see that it is different data.

For reference:
The debugging for the transaction: https://dashboard.tenderly.co/tx/rinkeby/0xc598c867a99955109e6439a6239a735bfe99e0f03e4f05b6e05aad0829d41085
The decoded data for the transaction: 
[https://rimeissner.dev/transaction-decoder/#/?data=0x8d80ff0a...](https://rimeissner.dev/transaction-decoder/#/?data=0x8d80ff0a00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000192095ea7b3000000000000000000000000c1f3af5dc05b0c51955804b2afc80ef8feed67b9ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff5ed8bd53b0c3fa3deabd345430b1a3a6a4e8bd7c0000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000044cc1b4bf600000000000000000000000011b0fd6914efa365ee77c5979dac068fef21db8f00000000000000000000000000000000000000000000000000000000000000640000000000000000000000005ed8bd53b0c3fa3deabd345430b1a3a6a4e8bd7c0000000000000000000000000000000000000000000000000000000061ab95320000000000000000000000000000000000000000000000000000000061abaefac1f3af5dc05b0c51955804b2afc80ef8feed67b900000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000a40000000000000000000000000000)

**Comment by rmeissner** [comment]
Regarding the `GS026` it seems that the Safe transaction data was adjusted after signing. E.g. the parameters in the call to the contracts are different to what was signed with the proposal.

The safe-tasks always use `safeTxGas` and `gasPrice` as `0`, but in https://rinkeby.etherscan.io/tx/0x2bfae98c2c13d30e0823fd6f75e4198bda0d792a3159ba4fe570a09e97364c42 both are set.
